name: SDK NuGet Publish

on:
  push:
    branches: [ master ]
    paths:
      - 'src/Sdk/**'
      - '**/Directory.Build.props'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/Sdk/**'
      - '**/Directory.Build.props'
  workflow_dispatch:

jobs:
  publish-milvaion-sdk:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: Restore Milvasoft.Milvaion.Sdk dependencies
        run: dotnet restore src/Sdk/Milvasoft.Milvaion.Sdk/Milvasoft.Milvaion.Sdk.csproj

      - name: Build Milvasoft.Milvaion.Sdk
        run: dotnet build src/Sdk/Milvasoft.Milvaion.Sdk/Milvasoft.Milvaion.Sdk.csproj --no-restore --configuration Release

      - name: Pack Milvasoft.Milvaion.Sdk
        run: dotnet pack src/Sdk/Milvasoft.Milvaion.Sdk/Milvasoft.Milvaion.Sdk.csproj --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o ./packages

      - name: Publish Milvasoft.Milvaion.Sdk to NuGet
        run: dotnet nuget push ./packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate

  publish-milvaion-sdk-worker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: Restore Milvasoft.Milvaion.Sdk.Worker dependencies
        run: dotnet restore src/Sdk/Milvasoft.Milvaion.Sdk.Worker/Milvasoft.Milvaion.Sdk.Worker.csproj

      - name: Build Milvasoft.Milvaion.Sdk.Worker
        run: dotnet build src/Sdk/Milvasoft.Milvaion.Sdk.Worker/Milvasoft.Milvaion.Sdk.Worker.csproj --no-restore --configuration Release

      - name: Pack Milvasoft.Milvaion.Sdk.Worker
        run: dotnet pack src/Sdk/Milvasoft.Milvaion.Sdk.Worker/Milvasoft.Milvaion.Sdk.Worker.csproj --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o ./packages

      - name: Publish Milvasoft.Milvaion.Sdk.Worker to NuGet
        run: dotnet nuget push ./packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
