name: Worker Template NuGet Publish

on:
  push:
    branches: [ master ]
    paths:
      - 'src/Workers/Milvasoft.Templates.Milvaion/**'
      - '**/Directory.Build.props'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/Workers/Milvasoft.Templates.Milvaion/**'
      - '**/Directory.Build.props'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: Restore Milvasoft.Templates.Milvaion dependencies
        run: dotnet restore src/Workers/Milvasoft.Templates.Milvaion/Milvasoft.Templates.Milvaion.csproj

      - name: Build Milvasoft.Templates.Milvaion
        run: dotnet build src/Workers/Milvasoft.Templates.Milvaion/Milvasoft.Templates.Milvaion.csproj --no-restore --configuration Release

      - name: Pack Milvasoft.Templates.Milvaion
        run: dotnet pack src/Workers/Milvasoft.Templates.Milvaion/Milvasoft.Templates.Milvaion.csproj --no-build --configuration Release -o ./packages

      - name: Publish Milvasoft.Templates.Milvaion to NuGet
        run: dotnet nuget push ./packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
